name: .NET test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  packages: read

jobs:
  test-release:
    strategy:
      matrix:
        rid: [
          linux-x64, linux-arm64,
          win-x64, osx-x64,
        ]
    runs-on: ubuntu-latest
    name: Test Release
    # needs: publish
    steps:
      - name: Download release
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          # fileName: ddns-bunny.net-${{ matrix.rid }}.zip
          fileName: ddns-bunny.net-1.0.3-${{ matrix.rid }}.zip
          extract: true
          out-file-path: release
      - run: |
          ls
          cd release
          ls
          count=$(ls | wc -l)
          if [ $count -ne $EXPECTED_COUNT ]; then
            echo "Expected $EXPECTED_COUNT files, found $count"
            exit 1
          fi
        env:
          EXPECTED_COUNT: 5
